FROM python:3

RUN pip3 install APScheduler==3.6.3 \
    certifi==2020.11.8 \
    cffi==1.14.3 \
    chardet==3.0.4 \
    click==7.1.2 \
    cryptography==3.2.1 \
    decorator==4.4.2 \
    Flask==1.1.2 \
    Flask-SQLAlchemy==2.4.4 \
    idna==2.10 \
    itsdangerous==1.1.0 \
    Jinja2==2.11.2 \
    MarkupSafe==1.1.1 \
    pycparser==2.20 \
    pyTelegramBotAPI==3.7.4 \
    python-telegram-bot==13.0 \
    pytz==2020.4 \
    requests==2.25.0 \
    six==1.15.0 \
    SQLAlchemy==1.3.20 \
    tornado==6.1 \
    tzlocal==2.1 \
    urllib3==1.26.2 \
    Werkzeug==1.0.1 \
    pyOpenSSL==20.0.0 \
    flask-cors==3.0.9

WORKDIR /opt/notification-service

COPY . .
