version: '3'
services:
  notification-service:
    container_name: notification-service
    build:
      context: .
    environment:
      - FLASK_APP=app.py
      - TELEGRAM_BOT_TOKEN=
      # Define messages for each message type
      - WELCOME_MESSAGE=Welcome, {{ USER_FULL_NAME }}! You are now able to configure {{ SERVICE_NAME }} via Telegram.
        Go to your dashboard and add the Telegram notification provider by entering this ID {{ USER_CHAT_ID }}.
      - UNKNOWN_MESSAGE=Sorry, {{ USER_FULL_NAME }}. I didn't understand you.
      # Use template variables (prefix TEMPLATE_VAR_)
      - TEMPLATE_VAR_SERVICE_NAME=COVID-19 incidence update notifications
    command: flask run --host=0.0.0.0 --port 443 --cert=cert/cert.pem --key=cert/key.pem
    ports:
      - 443:443
    volumes:
      # Include certificate dir needed for HTTPS support
      - ./cert/:/opt/notification-service/cert:ro
    restart: unless-stopped