swagger: "2.0"
info:
  description: "This is the api documentation for notification service."
  version: "1.0.0"
  title: "Notification service api documentation"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1"
basePath: "/"
tags:
- name: "notification"
  description: ""
schemes:
- "http"
paths:
  /notification:
    get:
      tags:
      - "notification"
      summary: "Get notifications"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "recipient"
        description: "Name of the recipient to get messages from."
        type: "string"
        required: false
      responses:
        "200":
          description: "Return found notifications in a list."
        "404":
          description: "Couldn't find notifications of specified recipient."
    post:
      tags:
      - "notification"
      summary: "Add new notification"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "formData"
        name: "recipient"
        description: "Name of the recipient to send a message to."
        type: "string"
        required: true
      - in: "formData"
        name: "msg"
        description: "Message to send"
        type: "string"
        required: true
      responses:
        "201":
          description: "Notification was created. This doesn't indicate that the message was successfully sent to Telegram."
        "400":
          description: "A required argument is missing."
  /notification/{notification_id}:
    get:
      tags:
      - "notification"
      summary: "Get notification"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "notification_id"
        description: "Notification id."
        type: "integer"
        required: true
      responses:
        "200":
          description: "Found notification with specified id."
          schema:
            $ref: "#/definitions/Notification"
        "404":
          description: "Couldn't find notifications with specified id."
definitions:
  Notification:
    type: "object"
    required:
    - "id"
    - "creation_date"
    - "recipient"
    - "msg"
    properties:
      id:
        type: "integer"
      creation_date:
        type: "string"
        example: "2020-12-02 20:49:36.653"
        description: "DateTime string in UTC time format."
      recipient:
        type: "string"
        example: "0123456789"
        description: "Telegram chat id"
      msg:
        type: "string"
        example: "This is a message."
        description: "Message to send to recipient."
      error_msg:
        type: "string"
        format: "json"
        example: '{"request_error": null, "status_code": 200, "telegram_response": {"ok": true, "result": {"message_id": 188, "from": {"id": 1408066607, "is_bot": true, "first_name": "bot_first_name", "username": "botusername"}, "chat": {"id": 12345678, "first_name": "Max", "username": "MaxMustermann", "type": "private"}, "date": 1606942176, "text": "This is a new message."}}}'
        description: "JSON response containing of three objects: `request_error`,
        `status_code` and `telegram_response`.
        `request_error` contains
        information if network error occurred while contacting Telegram API.
        `status_code` is the HTTP status code returned by Telegram API.
        `telegram_response` is a
        [response object](https://core.telegram.org/bots/api#making-requests)
        generated by Telegram API."
      error_msg_human_readable:
        type: "string"
        enum:
         - Connection error
         - General network error
         - Unknown error
        description: "Contains human readable error message if something went
        wrong during sending message to Telegram API."
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"