# Generated by Django 3.1.3 on 2020-11-26 15:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000000000000', max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscipted',
            field=models.BooleanField(default=False),
        ),
    ]
