# Generated by Django 3.1.3 on 2021-01-27 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorizationKey', models.CharField(default='0000000', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='Activate_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribtionId',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribtionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(default='0000000', max_length=300),
        ),
    ]
