# Generated by Django 3.1.3 on 2020-12-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201128_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscipted',
            field=models.BooleanField(default=True),
        ),
    ]
