# Generated by Django 3.1.3 on 2020-12-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201202_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribtionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscipted',
            field=models.BooleanField(default=False),
        ),
    ]
