# Generated by Django 3.1.3 on 2021-01-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201202_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscipted',
            new_name='Subscripted',
        ),
    ]
