# Generated by Django 3.1.3 on 2021-01-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210106_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorizationKey', models.CharField(default='0000000', max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Subscripted',
            new_name='subscripted',
        ),
    ]
