version: '3.5'
services:
  covid19-update-service:
    container_name: covid19-update-service
    build:
      context: ./covid19-update-service
    environment:
      - DB_TYPE=sqlite3
      - DB_SOURCE=storage.db?_foreign_keys=on
      - SERVER_PORT=9005
      - POLL_INTERVAL_MINUTES=5
      - TELEGRAM_CONTACT_URI=
      - TELEGRAM_AUTH0_AUD=
      - TELEGRAM_AUTH0_CLIENT_ID=
      - TELEGRAM_AUTH0_CLIENT_SECRET=
      - TELEGRAM_AUTH0_TOKEN_URL=
      - SENDGRID_API_KEY=
      - SENDGRID_EMAIL=
      - AUTH0_ISS=
      - AUTH0_AUD=