# Generated by Django 3.1.3 on 2020-11-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201125_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
